### ISSUE TITLE
Screen face seems unbalanced when time on bottom

### ISSUE THREAD

**Issue by fidian** [bhdouglass/simply-light#1]
I am using the new v2.7 that adds the feature I requested by email.  Thanks for getting that done so quickly!

The spacing seems off.  There is a large amount of padding above the weather and almost none below the time.  Would you please spread things out more or even out the padding?

**Comment by bhdouglass** [comment]
There is actually a good reason for the extra spacing at the top, that's where the batter percentage and AM/PM go. Obviously this doesn't make sense if you aren't using those features. I'll make it dynamic so it doesn't leave the space if it doesn't need to.

**Comment by bhdouglass** [comment]
I just released v2.8 to the pebble store, I've adjusted the layout some, I think it's looking better now. Let me know what you think!

**Comment by fidian** [comment]
Much better.  Thanks for balancing the display!

## 

Tyler Akins
